# 定义工作流的名称
name: Python Practice

# 定义触发条件：推送到 main 分支或手动触发
on:
  push:
    branches:
      - main
  workflow_dispatch:

# 定义具体的任务
jobs:
  python-practice:
    # 运行环境
    runs-on: ubuntu-latest

    steps:
      # 第一步：拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 第二步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 使用 Python 3.11

      # 第三步：安装依赖（如果有 requirements.txt 文件）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 第四步：运行 Python 脚本
      - name: Run Python script
        run: python your_script.py
